services:
  - type: web
    name: juris360
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 2 --threads 4 --timeout 120"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: ""   # keep empty to use SQLite
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
